version: '3.4'

services:
  melichallenge.api:
    image: ${DOCKER_REGISTRY-}melichallengeapi
    build:
      context: .
      dockerfile: MeLiChallenge.Api/Dockerfile
  postgres_image:
    image: postgres
    expose:
    - "5432"
    ports: 
      - "5432:5432"
    restart: always
    volumes: 
      - db_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "meliuser"
      POSTGRES_PASSWORD: "melipassword"
      POSTGRES_DB: "melidb"

volumes:
  db_volume: